version: '3'

#Declarar los servicios
#Cada servicio con la imagen ya creada
#expose para comunicacion interna y ports para exponer al exterior
#depends_on para ligar conexion entre contenedores
#Crear la red domain.calculus antes de ligarlos
#networks para agrupar los contenedores y solo se comuniquen entre esa red
services:
  catclientes:
    container_name: apiclientes
    image: api_clientes
    build: .
    ports:
      - '1000:1000'
    networks:
      - domain.parties
    depends_on:
      - database
  database:
      container_name: mongoserver
      image: mongo
      environment:
         - MONGO_INITDB_DATABASE=bc
         - MONGO_INITDB_ROOT_USERNAME=apiuser
         - MONGO_INITDB_ROOT_PASSWORD=apipassword
      volumes:
         - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      ports:
         - '27017:27017'
      networks:
         - domain.parties
networks:
   domain.parties:
     external: true
